### ISSUE TITLE
Practitioner Questions

### ISSUE THREAD

**Issue by tobiaskauer** [tkauer/facelift#12]
#### visualization
- spatial patterns: Where in Boston do beautiful places cluster?
- Explainability: What are segments, that are typically beautified?
- Explainability: What are segments, that are typically beautified?
- Biases: What are suggestions / conclusions made by the presentation of the data that you would not make on your own?

#### Process / ML
- Do you understand the process behind facelift?
- … (Sagar Help!)

#### Outcome
- What assumptions about urban beauty can one make with the help of facelift?
- What surprises you when looking at the beautified examples?
- Can you see possible future applications of this work?
- What problematic biases do you see within the method and the data?
- miriam: What explainability metrics would you add for completeness

**Comment by sagarjoglekar** [comment]
To build on this :
Process/ML:

- Do the 5 metrics give additional insights in an urban planning sense ? 

- If they do, does the valuation for them make sense for the examples at hand ? 

- Given the fact the the beautification is done by maximising the concept of beauty, as learned by the deep learning model, do you foresee any deviations from the norm as compared to human/textbook interpretations ? 

- Would you like to explore these methods for other urban design dimensions ? if yes what are they?


Outcome:

- Can the changes in transformations quantified in terms of real dollars ? 
- Roughly how often do you agree with the beautification transformations?

**Comment by tobiaskauer** [comment]
daniele: we should boil it down to 5 (to 7) questions.

**Comment by tobiaskauer** [comment]
#### tasks
- Can you with help of the application figure out, where in Boston beautiful / ugly areas cluster?
- Can you identify a general pattern of change for the process of beautification?
- Specificly, what are Segments that usually increase/decrease during beautification

#### outcome
- Do the 5 metrics give additional insights? What metrics would you add for measuring the changes before and after the beautification?
- Roughly, how often do you think the beautified images are actually more beautiful (Quantifiable)?
- Do you see any problematic biases in the data and its representation that leads to wrong conclusions?

**Comment by tobiaskauer** [comment]
### General Questions
- Name
- E-Mail-Adress
- Field of Practice
- **_Age?_**

### Patterns of Beauty
Select multiple labels on the map and consider that labels are ordered by beauty. Identify the areas that are beautiful and ugly. Select the true statement (multiple selection possible):
- [ ] West more beautiful than East
- [ ] East more beautiful than West
- [ ] North more beautiful than South
- [ ] South more beautiful than North
- [ ] South more beautiful than East
- [ ] North more beautiful than West
- [ ] I can not find any patterns.

### Urban Design Metrics
Explore several beautification examples. Based on the presented data, what urban design metrics are typically associated with beauty (multiple selection possible)?
- [ ]  Walkability
- [ ] Complexity
- [ ] Landmarks
- [ ] Greenspace
- [ ] Openness
- [ ] none of the above, but i would love to see how [________] performs.

### Urban Elements
Explore several beautification examples. What are urban elements, that typically increase during beautification?
- [ ] Trees
- [ ] Buildings
- [ ] Fences
- (... list all twelve elements here or just give an excerpt?)
- [ ] none of the above, but i would love to see how [________] performs.

### Urban Scenes
Explore several beautification examples. How helpful are the labels to you in order to understand, how this location has changed?
- [ ] very helpful
- [ ] a bit helpful
- [ ] not very helpful
- [ ] i don't understand what this is

### Beautification Accountability
Roughly, how often do you think the beautified images are actually more beautiful
- [ ] Everytime
- [ ] Most of the time
- [ ] Some times
- [ ] Never

### Data Accountability
Roughly, how often do you think the shown data (metrics, elements and scenes) actually describes the change seen in the images?
- [ ] Everytime
- [ ] Most of the time
- [ ] Some times
- [ ] Never

STILL TO BE DONE!!!! :

### Future Applications
What do you think are possible future applications of this technology?

### Biases
**_try to come up with tasks that lead to false conclusion_**
- [ ] ...
- [ ] ...
- [ ] ...

**Comment by tobiaskauer** [comment]
Damianos answers
<img width="961" alt="screen shot 2017-11-22 at 17 53 44" src="https://user-images.githubusercontent.com/28626912/33143100-ae5a2482-cfb0-11e7-9982-756304e0726c.png">
<img width="918" alt="screen shot 2017-11-22 at 17 53 49" src="https://user-images.githubusercontent.com/28626912/33143077-99da58d8-cfb0-11e7-82e1-6b9014e44cc9.png">

**Comment by tobiaskauer** [comment]
comments daniele:
- each (or some) of the questions could have a free text box saying 'explain why'
- also we could have a few open ended questions with free text boxes (to beef up the paper) on controversial issues
  - 1) assuming to have the perfect solution, what are the negative consequences of beautifying the world? (E.g. Gentrification)
  - 2) how this way of beautifying differs from existing practices 
  - 3) can we really beautify the world with machine learning ? Won't be transform places into "bland" average places (that is non places) 
  - 4) what if the data is biased
  - 5) which are the concrete applications ?
  - 6) does it help architects take better decisions
  - 7) does it help to think about a more participatory way of involving the public into the planning process ? 
  - 8) what s the use of showing which urban elements change in each beatified version?
  - 9) does the tool help explore the invisible parts of the city? Or to help people to know better their cities?
  - 10) can the tool raise awareness in city councils ? Among the general public?

**Comment by tobiaskauer** [comment]
comments damiano:

 Regarding the question I might be interested to know:
 - Do you think you would use the tool in your practice?
 - Do you think you might use it again?
 - Would you use the tool for decision making in your practice?
 - Did you actually understand how the system works?
